apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/twitter-on-k8s-postgres: "true"
        io.kompose.network/twitter-on-k8s-spring: "true"
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: CONFIG_SERVER_HOST
              value: config-server
            - name: DATASOURCE_HOST
              value: postgres
            - name: EUREKA_HOST
              value: eureka-server
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: ZIPKIN_HOST
              value: zipkin
          image: merikbest/twitter-spring-reactjs:user-service
          name: user-service
          ports:
            - containerPort: 8001
              hostPort: 8001
              protocol: TCP
      hostname: user-service
      restartPolicy: Always
