apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: image-service
  name: image-service
spec:
  ports:
    - name: "8021"
      port: 8021
      targetPort: 8021
  selector:
    io.kompose.service: image-service
